// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpxfsyyqnkbopcnaunea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweGZzeXlxbmtib3BjbmF1bmVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3Nzc3MDEsImV4cCI6MjA1NjM1MzcwMX0.Mq26xc4gUGXDsxVp1RLkA0Qew9MfFZl-_aioKJ8lNxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);